echoInterval: 0
minimumAge: 5
daysToKeepLogs: 60
worklistInterval: 30000
defaultTransferSyntax: JPEGLossless
maxDataBuffer: 1048776
storageTimeout: 900
expiryThreshhold: 604800
scpPort: 1040
minFreeSpace: 10
studyThreshold: 60
findScpPort: 1041
storageInterval: 5000
filters: mutate,sort
clientTimeout: 600
maxPDVsPerPDU: 1
maxClientsPerServer: 0
myAeTitle: SIEMENS_FLUX
dropUnfilteredInstances: false
worklistDays: 0
batchSize: 0
cachePath: X:\Cache
activationCode: ''
