activationCode: ''
autoSaveLineSpeed: false
batchSize: 0
cachePath: D:\Cache
clientTimeout: 600
daysToKeepLogs: 60
defaultTransferSyntax: ''
dropUnfilteredInstances: false
echoInterval: 0
expiryThreshhold: 604800
filters: route
findScpPort: 1041
maxClientsPerServer: 0
maxDataBuffer: 1048776
maxPDVsPerPDU: 1
minFreeSpace: 10
minimumAge: 5
minimumLineSpeed: 500
myAeTitle: FLUX_CAPACITOR
scpPort: 1040
storageInterval: 5000
studyThreshold: 0
worklistDays: 2
worklistInterval: 30000
