activationCode: ''
cachePath: X:\test\Cache\
scpPort: 2040
findScpPort: 2041
minimumAge: 5
daysToKeepLogs: 60
worklistInterval: 30000
defaultTransferSyntax: JPEGLossless  
worklistDays: 0
storageTimeout: 1800
expiryThreshhold: 604800
minFreeSpace: 10
filters: route,mutate
storageInterval: 5000
maxDataBuffer: 1048776
maxClientsPerServer: 0
myAeTitle: FLUX_CAPACITOR
dropUnfilteredInstances: false
batchSize: 0
maxPDVsPerPDU: 1
clientTimeout: 600
echoInterval: 0
studyThreshold: 0

