activationCode: ''
batchSize: 0
cachePath: X:\Cache\
clientTimeout: 600
daysToKeepLogs: 60
defaultTransferSyntax: JPEGLossless
dropUnfilteredInstances: false
echoInterval: 0
expiryThreshhold: 604800
filters: route,mutate,sort
findScpPort: 1041
maxClientsPerServer: 0
maxDataBuffer: 1048776
maxPDVsPerPDU: 1
minFreeSpace: 10
minimumAge: 5
myAeTitle: FLUX_CAPACITOR
scpPort: 1040
storageInterval: 5000
storageTimeout: 1800
studyThreshold: 120
worklistDays: 0
worklistInterval: 30000
