echoInterval: 0
minimumAge: 1
daysToKeepLogs: 60
worklistInterval: 30000
defaultTransferSyntax: JPEG2000Lossless
maxDataBuffer: 1048776
storageTimeout: 1800
expiryThreshhold: 604800
scpPort: 1040
minFreeSpace: 10
studyThreshold: 0
findScpPort: 1041
storageInterval: 5000
filters: ''
clientTimeout: 600
maxPDVsPerPDU: 1
maxClientsPerServer: 0
myAeTitle: REVMOBILE
dropUnfilteredInstances: false
worklistDays: 3
batchSize: 0
cachePath: X:\Cache
activationCode: ''
