activationCode: ''
batchSize: 0
cachePath: X:\Cache\
clientTimeout: 600
daysToKeepLogs: 60
defaultTransferSyntax: JPEG2000Lossless
dropUnfilteredInstances: false
echoInterval: 0
expiryThreshold: 604800
findScpPort: 1041
maxClientsPerServer: 0
maxDataBuffer: 1048776
maxPDVsPerPDU: 1
minFreeSpace: 10
minimumAge: 5
myAeTitle: FLUX_SERVER4
scpPort: 1040
storageInterval: 5000
studyThreshold: 1800
worklistDays: 0
worklistInterval: 0
