activationCode: ''
minimumAge: 5
daysToKeepLogs: 60
worklistInterval: 30000
echoInterval: 1000
defaultTransferSyntax: ''
worklistDays: 0
storageTimeout: 60
expiryThreshhold: 604800
scpPort: 1040
minFreeSpace: 10
filters: ''
findScpPort: 1041
storageInterval: 5000
maxDataBuffer: 1048776
maxClientsPerServer: 0
myAeTitle: FLUX_CAPACITOR
dropUnfilteredInstances: true
batchSize: 50
cachePath: X:\Cache
maxPDVsPerPDU: 1
