activationCode: ''
batchSize: 0
cachePath: X:\Cache\
clientTimeout: 600
daysToKeepLogs: 60
defaultTransferSyntax: JPEG2000Lossless
dropUnfilteredInstances: false
echoInterval: 0
expirationAge: 1000000
findScpPort: 1041
maxClientsPerServer: 0
maxDataBuffer: 1048776
maxPDVsPerPDU: 1
minFreeSpace: 15
minimumAge: 5
myAeTitle: FLUX_SERVER4
scpPort: 1040
skipFailedCompression: true
storageInterval: 5000
storageTimeout: 1800
storageTimeout: 60
worklistDays: 0
worklistInterval: 0
